apiVersion: v1
kind: Pod
metadata:
  name: debezium-connect
  namespace: mysql
spec:
  containers:
    - name: connect
      image: debezium/connect
      ports:
        - name: debezium
          containerPort: 8083
          protocol: TCP
      env:
        - name: BOOTSTRAP_SERVERS
          value: "one-node-cluster-0.one-node-cluster.redpanda.svc.cluster.local:9092"
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value:  "inventory.configs"
        - name: OFFSET_STORAGE_TOPIC
          value:  "inventory.offset"
        - name: STATUS_STORAGE_TOPIC
          value: "inventory.status"
