version: "2.3"
# Ubuntu , set this for redpanda to start
# https://sort.veritas.com/public/documents/HSO/2.0/linux/productguides/html/hfo_admin_ubuntu/ch04s03.htm

# Clickhouse Table Schema
# create table test(id int, message String) ENGINE=MergeTree() PRIMARY KEY id;
services:
  kafka:
    image: vectorized/redpanda
    ports:
      - "8081:8081"
      - "8082:8082"
      - "9091:9091"
      - "9092:9092"
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=root
      - CLICKHOUSE_DB=test
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"